# Generated by Django 2.2 on 2020-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('clientId', models.CharField(max_length=50, unique=True)),
                ('clientSecret', models.CharField(max_length=100, unique=True)),
                ('createdDatetime', models.DateTimeField(auto_now_add=True)),
                ('updatedDatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
