# Generated by Django 2.2 on 2020-02-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutationCode', models.CharField(blank=True, max_length=10, null=True)),
                ('firstName', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('streetName', models.CharField(max_length=55)),
                ('houseNumber', models.CharField(max_length=20)),
                ('houseNumberExtended', models.CharField(blank=True, max_length=10, null=True)),
                ('addressSupplement', models.CharField(blank=True, max_length=15, null=True)),
                ('extraAddressInformation', models.CharField(blank=True, max_length=20, null=True)),
                ('zipCode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('countryCode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
                ('vatNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('chamberOfCommerceNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('orderReference', models.CharField(blank=True, max_length=20, null=True)),
                ('deliveryPhoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportId', models.CharField(max_length=9)),
                ('transporterCode', models.CharField(
                    choices=[('BRIEFPOST', 'BRIEFPOST'), ('UPS', 'UPS'), ('TNT', 'TNT'), ('TNT_EXTRA', 'TNT_EXTRA'),
                             ('TNT_BRIEF', 'TNT_BRIEF'), ('TNT_EXPRESS', 'TNT_EXPRESS'), ('DYL', 'DYL'),
                             ('DPD_NL', 'DPD_NL'), ('DPD_BE', 'DPD_BE'), ('BPOST_BE', 'BPOST_BE'),
                             ('BPOST_BRIEF', 'BPOST_BRIEF'), ('DHLFORYOU', 'DHLFORYOU'), ('GLS', 'GLS'),
                             ('FEDEX_NL', 'FEDEX_NL'), ('FEDEX_BE', 'FEDEX_BE'), ('OTHER', 'OTHER'), ('DHL', 'DHL'),
                             ('DHL_DE', 'DHL_DE'), ('DHL_GLOBAL_MAIL', 'DHL_GLOBAL_MAIL'), ('TSN', 'TSN'),
                             ('FIEGE', 'FIEGE'), ('TRANSMISSION', 'TRANSMISSION'), ('PARCEL_NL', 'PARCEL_NL'),
                             ('LOGOIX', 'LOGOIX'), ('PACKS', 'PACKS'), ('COURIER', 'COURIER'), ('RJP', 'RJP')],
                    max_length=20)),
                ('trackAndTrace', models.CharField(blank=True, max_length=20, null=True)),
                ('shippingLabelId', models.CharField(blank=True, max_length=40, null=True)),
                ('shippingLabelCode', models.CharField(blank=True, max_length=15, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField()),
                ('shipmentDate', models.DateTimeField()),
                ('shipmentReference', models.CharField(blank=True, max_length=30, null=True)),
                ('fulfilmentMethod',
                 models.CharField(choices=[('FBB', 'Fulfilled By Bol.com'), ('FBR', 'Fulfilled By Retailer')],
                                  default='FBR', max_length=3)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('billingDetails',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingDetails',
                                   related_query_name='billingDetails', to='shipments.Customer')),
                ('customerDetails',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerDetails',
                                   related_query_name='customerDetails', to='shipments.Customer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailers.Retailer')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Transport')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderItemId', models.CharField(max_length=10)),
                ('orderId', models.CharField(max_length=10)),
                ('orderDate', models.DateTimeField()),
                ('latestDeliveryDate', models.DateTimeField()),
                ('ean', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('offerPrice', models.FloatField()),
                ('offerCondition', models.CharField(
                    choices=[('NEW', 'NEW'), ('OLD', 'OLD'), ('AS_NEW', 'AS_NEW'), ('GOOD', 'GOOD'),
                             ('REASONABLE', 'REASONABLE'), ('MODERATE', 'MODERATE')], max_length=3)),
                ('offerReference', models.CharField(blank=True, max_length=15, null=True)),
                ('fulfilmentMethod',
                 models.CharField(choices=[('FBB', 'Fulfilled By Bol.com'), ('FBR', 'Fulfilled By Retailer')],
                                  max_length=3)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('shipment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipmentItems',
                                   related_query_name='shipmentItems', to='shipments.Shipment')),
            ],
        ),
    ]
